version: 2.1

jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Start Docker
          command: |
            sudo service docker start
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Start Docker Containers
          command: |
            docker-compose -f docker-compose.test.yml up -d
      - run:
          name: Stop and remove Docker Containers
          command: |
            docker-compose -f docker-compose.test.yml down

  release:
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - run:
          name: Release
          command: |
            if [[ $(git rev-parse --abbrev-ref HEAD) == "main" ]]; then
              npm install -g semantic-release @semantic-release/github @semantic-release/git @semantic-release/commit-analyzer @semantic-release/npm @semantic-release/release-notes-generator
              semantic-release
            else
              echo "Not on main branch, skipping release."
            fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  release:
    jobs:
      - release